name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - "src/examples/module1/rust_app"
          - "src/examples/module2/1-memory-safety/rust_app"
          - "src/examples/module2/1-memory-safety/rust_app_memory_demo"
          - "src/examples/module2/2-sustainability/rust_app"
          - "src/examples/module4/rust_app"
          - "src/examples/module5/rust_app"
          - "src/examples/module6/rust_app"
          - "src/examples/module7/rust_app"
          - "src/examples/module8/rust_app"
          - "src/examples/module9/rust_app"
          - "src/examples/module10/rust_app"
          - "src/solutions/module1/rust_app"
          - "src/solutions/module2/1-memory-safety/rust_app"
          - "src/solutions/module2/1-memory-safety/rust_app_memory_demo"
          - "src/solutions/module2/2-sustainability/rust_app"
          - "src/solutions/module3/rust_app"
          - "src/solutions/module4/rust_app"
          - "src/solutions/module5/rust_app"
          - "src/solutions/module6/rust_app"
          - "src/solutions/module7/rust_app"
          - "src/solutions/module8/rust_app"
          - "src/solutions/module9/rust_app"
          - "src/solutions/module10/rust_app"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
        working-directory: ${{ matrix.project }}